
name: node.js.yml

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: ls
    - run: sudo systemctl stop n.service
    - run: npm i --legacy-peer-deps
    - run: npm run build
    - run: sudo systemctl start n.service
